.TH qtpovray 1 "June 2018" "Dick Balaska" "Version 3.80.11" \" -*- nroff -*-
.\" man page written by Andreas Dilger
.\" updated by Mark Gordon for POV-Ray 3.5
.\" updated by Nicolas Calimet and Christoph Hormann for POV-Ray 3.6
.\" updated by James Holsenback for POV-Ray 3.7
.\" updated by William F. Pokorny and Christoph Lipka for POV-Ray 3.7.1
.\" port to qtpovray by Dick Balaska

.SH NAME
qtpovray \- POV\-Ray with GUI

.SH SYNOPSIS
\fBqtpovray\fP [\fB-version\fe\fP]

.SH DESCRIPTION
\fBqtpovray\fP provides an integrated GUI (IDE) for developing \fBPOV\-Ray\fP
scenes.
.LP
\fBPOV\-Ray\fP is a free, full\-featured ray tracer, written and maintained
by a team of volunteers on the Internet.  
.LP
http://www.buckosoft.com/qtpovray
.LP
http://www.povray.org

.SH OPTIONS
When \fBqtpovray\fP is started, the gui is presented to the user.
The only option is
.TP
\fB\-version\fP
Print the qtpovray version and exit.

.SH SEE ALSO
qtpovray documentation at:
  http://www.buckosoft.com/qtpovray
.LP
.BR povray (1)
.LP
POV-Ray full documentation at:
  http://wiki.povray.org/content/Documentation:Contents

