#!/bin/bash
# stageqtpovray.sh
# A Cygwin script to setup the staged directory for Windows nsis installer

STAGEDIR=/c/Users/dick/staged/qtpovray
#EXEDIR=


FILEINC=$STAGEDIR/finclude.nsh
FILEINCUN=$STAGEDIR/fincludeUn.nsh
FILEINS=$STAGEDIR/finsert.nsh
FILEINSUN=$STAGEDIR/finsertUn.nsh

if [ ! -f stageqtpovray.sh ]; then
	echo "Run this script from its directory"
	exit 1
fi
if [ ! -d $STAGEDIR ]; then
	echo "$STAGEDIR does not exist"
	exit 2
fi
SCRIPTDIR=`pwd`
cd ../..
MASTERDIR=`pwd`
echo  "MASTERDIR=$MASTERDIR"
cp $MASTERDIR/qt/install/qtpovray.nsi $STAGEDIR
rm -rf $STAGEDIR/include
rm -rf "$STAGEDIR/Insert Menu"
cp -rp distribution/include $STAGEDIR

cd $STAGEDIR/include
echo ";finclude.nsh - generated by stageqtpovray" > $FILEINC
echo ";fincludeUn.nsh - generated by stageqtpovray" > $FILEINCUN
for f in * ; do
	echo "File \"include\\$f\"" >>$FILEINC
	echo "Delete \"\$DataDir\\include\\$f\"" >>$FILEINCUN
done


##########################################################
function processFile {
	local D=$1
	local F=$2
	#echo "File D=$D F=$F"
	echo "File \"Insert Menu\\$D\\$F\"" >> $FILEINS
	echo "Delete \"\$DataDir\\Insert Menu\\$D\\$F\"" >> $FILEINSUN
}

function processDir {
	local D=$1
	local F=$2
	#echo "Dir D=$D F=$F"
	local DIR="$D\\$F"
	if [ -z "$D" ]; then
		local DIR="$F"
	fi
	local OLDDIR=`pwd`
	cd "$STAGEDIR/Insert Menu/$DIR"
	#echo "SetOutPath \"\$DataDir\\$DIR\"" 
	echo "SetOutPath \"\$DataDir\\Insert Menu\\$DIR\"" >> $FILEINS
	local f

	for f in * ; do
		if [ -d "$f" ]; then
			processDir "$DIR" "$f"
		else
			processFile "$DIR" "$f"
		fi
	done
	echo "RMDir \"\$DataDir\\Insert Menu\\$DIR\"" >> $FILEINSUN
	cd "$OLDDIR"
	echo "SetOutPath \"\$DataDir\\Insert Menu\\$D\"" >> $FILEINS
}

##########################################################
cd "$MASTERDIR/distribution/platform-specific/windows"
cp -rp "Insert Menu" "$STAGEDIR/Insert Menu"
echo ";finsert.nsh - generated by stageqtpovray" > $FILEINS
echo "; manage the Insert Menu selections" >> $FILEINS
echo ";finsertUn.nsh - generated by stageqtpovray" > $FILEINSUN


cd "$STAGEDIR/Insert Menu"
for f in * ; do
	if [ -d "$f" ]; then
		processDir "" "$f"
	else
		processFile "" "$f"
	fi
done
