#!/bin/bash
# stageqtpovray.sh
# A Cygwin script to setup the staged directory for Windows nsis installer

STAGEDIR=/c/Users/dick/staged/qtpovray
QTBUILDDIR="build-qtpovray-Desktop_Qt_5_15_2_MSVC2015_64bit-Release"


FILEINC=$STAGEDIR/finclude.nsh
FILEINCUN=$STAGEDIR/fincludeUn.nsh
FILEINS=$STAGEDIR/finsert.nsh
FILEINSUN=$STAGEDIR/finsertUn.nsh
FILEQTH=$STAGEDIR/fqthelp.nsh
FILEQTHUN=$STAGEDIR/fqthelpUn.nsh
FILESCN=$STAGEDIR/fscenes.nsh
FILESCNUN=$STAGEDIR/fscenesUn.nsh

DEBUG=0

VIRGIN="N"

if [ ! -f stageqtpovray.sh ]; then
	echo "Run this script from its directory"
	exit 1
fi
if [ ! -d $STAGEDIR ]; then
	echo -n "$STAGEDIR does not exist. Create? [Y/N] "
	read YN
	if [ "$YN" != "Y" -a "$YN" != "y" ]; then
		exit 2
	fi
	mkdir -p $STAGEDIR
	if [ ! -d "$STAGEDIR" ]; then
		echo "Failed to create $STAGEDIR"
		exit 3
	fi
	VIRGIN="Y"

fi
SCRIPTDIR=`pwd`
cd ../..
MASTERDIR=`pwd`
echo  "MASTERDIR=$MASTERDIR"

cp ../$QTBUILDDIR/qt/gui/release/qtpovray.exe $STAGEDIR

if [ $VIRGIN = Y ]; then
	cd $STAGEDIR
	cp $MASTERDIR/qt/install/doWinDeployQt.bat .
	cmd /c doWinDeployQt.bat
fi
cp $MASTERDIR/qt/install/qtpovray.nsi $STAGEDIR
cp $MASTERDIR/LICENSE $STAGEDIR
rm -rf $STAGEDIR/include
rm -rf "$STAGEDIR/fonts"
rm -rf "$STAGEDIR/Insert Menu"
rm -rf "$STAGEDIR/qtpovrayHelp"
cd $MASTERDIR
cp -rp distribution/include $STAGEDIR
cp -rp distribution/qt/qtpovrayHelp $STAGEDIR
cp -rp qt/install/fonts $STAGEDIR

echo "include:"
cd $STAGEDIR/include
echo ";finclude.nsh - generated by stageqtpovray" > $FILEINC
echo ";fincludeUn.nsh - generated by stageqtpovray" > $FILEINCUN
for f in * ; do
	echo "File \"include\\$f\"" >>$FILEINC
	echo "Delete \"\$DataDir\\include\\$f\"" >>$FILEINCUN
done


##########################################################
function processInsertFile {
	local D=$1
	local F=$2
	if [ $DEBUG = 1 ]; then
		echo "File D=$D F=$F"
	fi
	echo "File \"$SECTIONDIR\\$D\\$F\"" >> $_FILEIN
	echo "Delete \"\$DataDir\\$SECTIONDIR\\$D\\$F\"" >> $_FILEOUT
}

function processInsertDir {
	local D=$1
	local F=$2
	if [ $DEBUG = 1 ]; then
		echo "Dir D=$D F=$F"
	fi
	local DIR="$D\\$F"
	if [ -z "$D" ]; then
		local DIR="$F"
	fi
	local OLDDIR=`pwd`
	cd "$STAGEDIR/$SECTIONDIR/$DIR"
	if [ $DEBUG = 1 ]; then
		echo "SetOutPath \"\$DataDir\\$DIR\"" 
	fi
	echo "SetOutPath \"\$DataDir\\$SECTIONDIR\\$DIR\"" >> $_FILEIN
	local f

	for f in * ; do
		if [ -d "$f" ]; then
			processInsertDir "$DIR" "$f"
		else
			processInsertFile "$DIR" "$f"
		fi
	done
	echo "RMDir \"\$DataDir\\$SECTIONDIR\\$DIR\"" >> $_FILEOUT
	cd "$OLDDIR"
	echo "SetOutPath \"\$DataDir\\$SECTIONDIR\\$D\"" >> $_FILEIN
}

##########################################################
echo "Insert Menu:"
cd "$MASTERDIR/distribution/platform-specific/windows"
cp -rp "Insert Menu" "$STAGEDIR/Insert Menu"
echo ";finsert.nsh - generated by stageqtpovray" > $FILEINS
echo "; manage the Insert Menu selections" >> $FILEINS
echo ";finsertUn.nsh - generated by stageqtpovray" > $FILEINSUN


SECTIONDIR="Insert Menu"
_FILEIN=$FILEINS
_FILEOUT=$FILEINSUN
cd "$STAGEDIR/$SECTIONDIR"
for f in * ; do
	if [ -d "$f" ]; then
		processInsertDir "" "$f"
	else
		processInsertFile "" "$f"
	fi
done

##########################################################
echo "qtpovray help:"
echo ";fqthelp.nsh - generated by stageqtpovray" > $FILEQTH
echo ";fqthelpUn.nsh - generated by stageqtpovray" > $FILEQTHUN
SECTIONDIR="qtpovrayHelp"
_FILEIN=$FILEQTH
_FILEOUT=$FILEQTHUN
cd "$STAGEDIR/$SECTIONDIR"
for f in * ; do
	if [ $DEBUG = 1 ]; then
		echo "Doing $f"
	fi
	if [ -d "$f" ]; then
		processInsertDir "" "$f"
	else
		processInsertFile "" "$f"
	fi
done

##########################################################
echo "sample scenes:"
cd "$MASTERDIR/distribution"
cp -rp "scenes" "$STAGEDIR/scenes"
echo ";fscenes.nsh - generated by stageqtpovray" > $FILESCN
echo ";fscenesUn.nsh - generated by stageqtpovray" > $FILESCNUN
SECTIONDIR="scenes"
_FILEIN=$FILESCN
_FILEOUT=$FILESCNUN
cd "$STAGEDIR/$SECTIONDIR"
for f in * ; do
	if [ $DEBUG = 1 ]; then
		echo "Sceneing $f"
	fi
	if [ -d "$f" ]; then
		processInsertDir "" "$f"
	else
		processInsertFile "" "$f"
	fi
done

cd $STAGEDIR
/c/Program\ Files\ \(x86\)/NSIS/Bin/makensis.exe qtpovray.nsi

